sudo: false
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
addons:
  chrome: stable
node_js:
- 10.6.0
matrix:
  fast_finish: true
before_install:
- npm cache verify
- npm prune
- npm update
install:
- npm install
script:
- npm run ci:travis

before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  on:
    branch: master
    tags: true
  token:
    secure: "LoXAi3tzxczKsLCYjdii0Rf3zrjJO1GZ8d0rlr5FJru3ZorfXj1ukVhMiczM73GH+14pNRVonIW91HdD1PesSceaMv4/nmCCEZOjLuukU/qEcPkGi5i7V7Jtzz1TPG4Bvl2G1YgxPeDlKun1NXV8miqrWQVuo+FKYu0D61FXXcWQ5Bji/OOV2qudj5GYOjblsqJU+xRH60OiaG2XAcegN9M/J8Lfv/i66vDKwBIyQ/d37LfwwK2RPWS6vxz4kZlLf4LRvdIjMRu/8UkCeRJVaJ9pxKArxypuw73fC++8CvKyM99a53tUvEGVM3Nz7kWdpRBDbzY8YEuZZDaWki2t1CICKkmn4wYXkwp7rkQ/KnVIF375fZkqMIQdpoOXbPTPY/YFtUG8zLHk9A+X4Cjnbk7MCodm6SSfSCid5AXuiC397Gucf6W0qBYgt75tX0WPvWfZyATbs7YqDdOSPREoeCuezbau8SEejELUteaSlR5HY1BVwgPIjN6ujSFxqrDhqCOfb6wmKgfiMGFbfxle6uLmMI0c/rKofZDanHKZCtYKYozuZEqT2W4Xr+qmvaHiGLOHq5FNh3lfJLge9Bb40wep20MGK+ss1F8r+TwqQspwOk/1AtsZPU54YRU1F+UCYqP7J2kwtgfUzLevQbZCweBUDL2kLwhQqkBQk2aTfsI="
    project: "siteervan"
    message: "Deployement sur le site d'Ervan"
before_deploy: "echo 'Fin!'"
