sudo: false
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
addons:
  chrome: stable
node_js:
- 10.6.0
matrix:
  fast_finish: true

  branches:
    only:
        -master

before_install:
- npm cache verify
- npm prune
- npm update
install:
- npm install

before_script:
- npm install -g firebase-tools

script:
- npm run ci:travis
- npm
- ng build --prod

after_success:
- firebase deploy --token $FIREBASE_TOKEN
